name: zeronet
version: 0.6.4-r3671
summary: Open, free and uncensorable websites
description: |
  Decentralized websites using Bitcoin crypto and the BitTorrent network - https://zeronet.io
  Why?
  We believe in open, free, and uncensored network and communication.
  No single point of failure: Site remains online so long as at least 1 peer is serving it.
  No hosting costs: Sites are served by visitors.
  Impossible to shut down: It's nowhere because it's everywhere.
  Fast and works offline: You can access the site even if Internet is unavailable.

grade: stable
confinement: strict

apps:
  zeronet:
    command: launcher.py
    plugs: [network,network-bind]
  tor:
    command: tor.py
    plugs: [network,network-bind]
parts:
  bundle:
    after:
      - source
    prime:
      - usr
      - bin
      - lib
      - include
      - etc
      - -usr/share/doc
      - -usr/share/man
      - -requirements.txt
      - -.gitignore
    source: snap/bundle
    plugin: python
    python-version: python2
    requirements: $SNAPCRAFT_STAGE/../parts/source/src/requirements.txt
  source:
    source: https://github.com/HelloZeroNet/ZeroNet
    source-commit: 5158a710dc6fffb3d8a1d1165f11c56f91298296
    source-type: git
    organize:
      update.py: upstream.update.py
      update.pyc: upstream.update.pyc
    override-build: |
      sed 's/self.plugin_path = "plugins"/self.plugin_path = os.environ["SNAP_USER_COMMON"]+"\/plugins"/g' -i src/Plugin/PluginManager.py
      python2 -m py_compile $(find -type f -iname "*.py" -print)
      cp -rp $PWD/* "$SNAPCRAFT_PART_INSTALL"
    filesets:
      main:
        - src
        - tools
        - plugins
        - zeronet.py
        - zeronet.pyc
        - start.py
        - start.pyc
        - requirements.txt
    stage:
      - $main
    prime:
      - $main
    plugin: dump
  scripts:
    source: snap/scripts
    after:
      - bundle
      - source
    filesets:
      scripts:
        - launcher.py
        - tor.py
        - torrc
        - update.py
    stage:
      - $scripts
    prime:
      - $scripts
    plugin: dump
    override-build: |
      python2 -m py_compile $(find -type f -iname "*.py" -print)
      cp -rp $PWD/* "$SNAPCRAFT_PART_INSTALL"
  tor:
    source: https://git.torproject.org/tor.git
    source-tag: tor-0.3.3.9
    source-type: git
    plugin: autotools
    configflags: [--disable-asciidoc]
    stage-packages:
      - libevent-dev
    build-packages:
      - git
      - build-essential
      - automake
      - libevent-dev
      - libssl-dev
